services:
  backend:
    build: backend
    ports:
      - "9292:9292"
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./backend:/app
    restart: on-failure

  db:
    image: postgres:14
    env_file: .env
    ports:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure


  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: on-failure


volumes:
  backend:
  pgdata: