source "https://rubygems.org"

gem "connection_pool", "~> 2.5"
gem "pg"
gem "puma"
gem "rackup"
gem "rubocop", require: false
gem "sinatra"

group :test do
  gem "rack-test"
  gem "rspec"
end

group :development do
  gem "sinatra-contrib"
end
