source "https://rubygems.org"

# gem "bcrypt"
gem "connection_pool", "~> 2.5"
gem "openssl", "~> 3.3"
gem "pg"
gem "puma"
gem "rackup"
gem "rubocop", require: false
gem "sinatra"

group :test do
  gem "rack-test"
  gem "rspec"
end

group :development do
  gem "pry", "~> 0.15.0"
  gem "pry-byebug"
  gem "sinatra-contrib"
end
